### ISSUE TITLE
Problem during creating index with anserini

### ISSUE THREAD

**Issue by caijie12138** [thunlp/COVID19-IRQA#1]
when I execute:
```
./indexer/bm25_indexer/bin/IndexCollection -collection JsonCollection -es -es.index cord19 -input collection -generator LuceneDocumentGenerator -threads 1 -storePositions -storeDocvectors -storeRawDocs
```
Following Error Message Occurs:
```
2020-04-07 00:29:09,951 INFO  [main] index.IndexCollection (IndexCollection.java:621) - Setting log level to INFO
2020-04-07 00:29:09,953 INFO  [main] index.IndexCollection (IndexCollection.java:624) - Starting indexer...
2020-04-07 00:29:09,953 INFO  [main] index.IndexCollection (IndexCollection.java:625) - ============ Loading Parameters ============
2020-04-07 00:29:09,953 INFO  [main] index.IndexCollection (IndexCollection.java:626) - DocumentCollection path: /root/caijie/COVID19-IRQA/data/CORD-19/
2020-04-07 00:29:09,954 INFO  [main] index.IndexCollection (IndexCollection.java:627) - CollectionClass: JsonCollection
2020-04-07 00:29:09,954 INFO  [main] index.IndexCollection (IndexCollection.java:628) - Generator: LuceneDocumentGenerator
2020-04-07 00:29:09,954 INFO  [main] index.IndexCollection (IndexCollection.java:629) - Threads: 1
2020-04-07 00:29:09,954 INFO  [main] index.IndexCollection (IndexCollection.java:630) - Stemmer: porter
2020-04-07 00:29:09,955 INFO  [main] index.IndexCollection (IndexCollection.java:631) - Keep stopwords? false
2020-04-07 00:29:09,955 INFO  [main] index.IndexCollection (IndexCollection.java:632) - Store positions? true
2020-04-07 00:29:09,955 INFO  [main] index.IndexCollection (IndexCollection.java:633) - Store docvectors? true
2020-04-07 00:29:09,955 INFO  [main] index.IndexCollection (IndexCollection.java:634) - Store transformed docs? false
2020-04-07 00:29:09,956 INFO  [main] index.IndexCollection (IndexCollection.java:635) - Store raw docs? true
2020-04-07 00:29:09,956 INFO  [main] index.IndexCollection (IndexCollection.java:636) - Optimize (merge segments)? false
2020-04-07 00:29:09,956 INFO  [main] index.IndexCollection (IndexCollection.java:637) - Whitelist: null
2020-04-07 00:29:09,956 INFO  [main] index.IndexCollection (IndexCollection.java:647) - Indexing into Elasticsearch...
2020-04-07 00:29:09,957 INFO  [main] index.IndexCollection (IndexCollection.java:648) - Elasticsearch batch size: 1000
2020-04-07 00:29:09,957 INFO  [main] index.IndexCollection (IndexCollection.java:649) - Elasticsearch index: cord19
2020-04-07 00:29:09,957 INFO  [main] index.IndexCollection (IndexCollection.java:650) - Elasticsearch hostname: localhost
2020-04-07 00:29:09,957 INFO  [main] index.IndexCollection (IndexCollection.java:651) - Elasticsearch host port: 9200
2020-04-07 00:29:09,958 INFO  [main] index.IndexCollection (IndexCollection.java:652) - Elasticsearch client connect timeout (in ms): 600000
2020-04-07 00:29:09,958 INFO  [main] index.IndexCollection (IndexCollection.java:653) - Elasticsearch client socket timeout (in ms): 600000
2020-04-07 00:29:09,958 INFO  [main] index.IndexCollection (IndexCollection.java:654) - Elasticsearch pool size: 10
2020-04-07 00:29:09,958 INFO  [main] index.IndexCollection (IndexCollection.java:655) - Elasticsearch user: elastic
2020-04-07 00:29:09,968 INFO  [main] index.IndexCollection (IndexCollection.java:707) - ============ Indexing Collection ============
2020-04-07 00:29:09,968 INFO  [main] index.IndexCollection (IndexCollection.java:760) - Thread pool with 1 threads initialized.
2020-04-07 00:29:09,968 INFO  [main] index.IndexCollection (IndexCollection.java:762) - Initializing collection in /root/caijie/COVID19-IRQA/data/CORD-19
2020-04-07 00:29:09,972 INFO  [main] index.IndexCollection (IndexCollection.java:765) - 4 files found
2020-04-07 00:29:09,972 INFO  [main] index.IndexCollection (IndexCollection.java:766) - Starting to index...
2020-04-07 00:29:10,072 ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:536) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: JSON document has no "id" field
	at io.anserini.collection.JsonCollection$Document.id(JsonCollection.java:152) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.generator.LuceneDocumentGenerator.createDocument(LuceneDocumentGenerator.java:105) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:468) [anserini-0.7.3-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-04-07 00:29:10,085 ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:536) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: JSON document has no "id" field
	at io.anserini.collection.JsonCollection$Document.id(JsonCollection.java:152) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.generator.LuceneDocumentGenerator.createDocument(LuceneDocumentGenerator.java:105) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:468) [anserini-0.7.3-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-04-07 00:29:10,087 ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:536) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: JSON document has no "id" field
	at io.anserini.collection.JsonCollection$Document.id(JsonCollection.java:152) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.generator.LuceneDocumentGenerator.createDocument(LuceneDocumentGenerator.java:105) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:468) [anserini-0.7.3-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-04-07 00:29:10,090 ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:536) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: JSON document has no "id" field
	at io.anserini.collection.JsonCollection$Document.id(JsonCollection.java:152) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.generator.LuceneDocumentGenerator.createDocument(LuceneDocumentGenerator.java:105) ~[anserini-0.7.3-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:468) [anserini-0.7.3-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-04-07 00:29:10,091 INFO  [main] index.IndexCollection (IndexCollection.java:850) - Indexing Complete! 0 documents indexed
2020-04-07 00:29:10,091 INFO  [main] index.IndexCollection (IndexCollection.java:851) - ============ Final Counter Values ============
2020-04-07 00:29:10,092 INFO  [main] index.IndexCollection (IndexCollection.java:852) - indexed:                0
2020-04-07 00:29:10,092 INFO  [main] index.IndexCollection (IndexCollection.java:853) - unindexable:            0
2020-04-07 00:29:10,092 INFO  [main] index.IndexCollection (IndexCollection.java:854) - empty:                  0
2020-04-07 00:29:10,092 INFO  [main] index.IndexCollection (IndexCollection.java:855) - skipped:                0
2020-04-07 00:29:10,093 INFO  [main] index.IndexCollection (IndexCollection.java:856) - errors:                 0
2020-04-07 00:29:10,097 INFO  [main] index.IndexCollection (IndexCollection.java:859) - Total 0 documents indexed in 00:00:00
```

Can you help me to solve it?

**Comment by zkt12** [comment]
The json collection you used is required 'id' and 'contents' keys for indexing.
